language: cpp
dist: xenial

matrix:
  include:
  - os: linux
    compiler: gcc

    before_install:
      - wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
      - sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-xenial.list http://packages.lunarg.com/vulkan/lunarg-vulkan-xenial.list
      - sudo apt update
      - sudo apt install vulkan-sdk
    script:
      - mkdir build
      - cd build
      - cmake ..
      - make
  - os: windows
    env:
      - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
    before_install:
      - curl --silent --show-error --output vulkan-sdk.exe https://sdk.lunarg.com/sdk/download/1.1.106.0/windows/vulkan-sdk.exe?Human=true
      - echo "cmd /min /C \"set __COMPAT_LAYER=RUNASINVOKER && start /wait \" .\vulkan-sdk.exe /S && exit" > test.bat
      - ./test.bat
      - cd C:/VulkanSDK/1.1.106.0
      - cd -
      - export VULKAN_SDK=C:\\VulkanSDK\\1.1.106.0
      - echo $VULKAN_SDK
      - env
    script:
      - export PATH=$MSBUILD_PATH:$PATH
      - mkdir build
      - cd build
      - cmake -G"Visual Studio 15 2017 Win64" ..
      - MSBuild.exe VulkanRendering.sln
