language: cpp
dist: xenial

matrix:
  include:
  - os: linux
    compiler: gcc

    before_install:
      - wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
      - sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-xenial.list http://packages.lunarg.com/vulkan/lunarg-vulkan-xenial.list
      - sudo apt update
      - sudo apt install vulkan-sdk
	  
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
